provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  bert-classify:
    lang: pydatascience
    handler: ./bert-classify
    image: anishellore5/bert-classify:latest
    environment:
      MODEL_NAME: RESNET
      MAX_JSON_SIZE: '1mb'
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 5
      com.openfaas.scale.zero: "true"
      com.openfaas.scale.zero-duration: "1m"
